name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_ai: ^3.7.0
  firebase_storage: ^13.0.6
  intl: ^0.20.2
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.3
  google_fonts: ^8.0.1
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: true
  ios: true
  web:
    enable: true
  image_path: "assets/images/crayon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
