
name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  google_fonts: ^8.0.1
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.2
  flutter_colorpicker: ^1.1.0
  camera: ^0.11.3
  path: ^1.9.1
  go_router: ^17.1.0
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: true
  ios: true
  web:
    enable: true
  image_path: "assets/images/my_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

google_fonts:
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
  output_dir: assets/fonts
